spring:
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      platform: h2
server:
  port: 8080

